webrest:
  build: job-schedule-api
  ports:
    - "8080"
    - "1221"
  links:
    - db:devpostgres

db:
  image: andreagrandi/postgresql:9.3
  volumes_from:
    - dbdata
  ports:
    - "5432:5432"

dbdata:
  image: andreagrandi/postgresql:9.3
  volumes:
    - /var/lib/postgresql
  command: true
