webrest:
  build: job-schedule-api
  ports:
    - "80:8080"
    - "1221:1221"
  links:
    - postgres:devpostgres.cne

postgres:
  image: postgres:latest
  environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
  volumes_from:
    - dbdata
  ports:
    - "5432:5432"

dbdata:
  image: postgres:latest
  volumes:
    - /var/lib/postgresql
  command: "true"
