webrest:
  restart: always
  build: job-schedule-service
  ports:
    - "80:8080"
    - "1221:1221"
  links:
    - postgres:devpostgres.cne
    - batchImport:batchImport.cne

batchImport:
  restart: always
  build: job-schedule-service
  ports:
      - "8080:8080"
      - "1221:1221"
  links:
      - postgres:devpostgres.cne

dbdata:
  restart: always
  image: postgres:latest
  volumes:
    - /var/lib/postgresql
  command: "true"

postgres:
  restart: always
  image: postgres:latest
  environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
  volumes_from:
    - dbdata
  ports:
    - "5432:5432"
