webrest:
  restart: always
  build: schedule-service
  ports:
    - "80:8080"
    - "1221:1221"
  links:
    - postgres:devpostgres.cne
    - engineService1:engineService1.cne

engineService1:
  restart: always
  build: engine-service
  ports:
      - "8080:8080"
      - "1221:1221"
  environment:
    application.engine.id: 2

dbdata:
  restart: always
  image: postgres:latest
  volumes:
    - /var/lib/postgresql
  command: "true"

postgres:
  restart: always
  image: postgres:latest
  environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
  volumes_from:
    - dbdata
  ports:
    - "5432:5432"
