schedule-service:
  restart: always
  build: schedule-service
  ports:
    - "80:8080"
    - "1221:1221"
  links:
    - postgres:devpostgres.cne
    - engine-service1:engine-servicex1.cne
    - engine-service2:engine-servicex2.cne

engine-service1:
  restart: always
  build: engine-service
  ports:
      - "8080:8080"
      - "1222:1222"
  environment:
    application.engine.id: 1

engine-service2:
  restart: always
  build: engine-service
  ports:
      - "9080:8080"
      - "1223:1222"
  environment:
    application.engine.id: 2

dbdata:
  restart: always
  image: postgres:latest
  volumes:
    - /var/lib/postgresql
  command: "true"

postgres:
  restart: always
  image: postgres:latest
  environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
  volumes_from:
    - dbdata
  ports:
    - "5432:5432"
