# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# See http://symfony.com/fr/doc/current/components/yaml/yaml_format.html
# See http://codebeautify.org/yaml-validator
# For deployment in Docker containers
spring:
    profiles:
       active: docker
spring.jpa:
    database: POSTGRESQL
    hibernate.ddl-auto: update
spring.datasource:
        url: jdbc:postgresql://devpostgres.cne:5432/docker
        driver-class-name: org.postgresql.Driver
        username: docker
        password: docker
        poolName: SpringBootHikariCP
        maximumPoolSize: 5
        minimumIdle: 3
        maxLifetime: 2000000
        connectionTimeout: 30000
        idleTimeout: 30000
        pool-prepared-statements: true
        max-open-prepared-statements: 250

server:
    port: 8080
